### ISSUE TITLE
关于puzzle目录下的yml文件中tune的设置

### ISSUE THREAD

**Issue by SleepyAsh0191** [kawa-yoiko/medle#10]
最近对这个项目挺感兴趣，并且也尝试着出了一些属于自己的谜题，但是本人比较疑惑的是，有的谜题会有类似于重复播放某一组音符的设定【例如谜题179，173】。

然后发现相应的yml里面的部分数组为负数，那么本人有一点疑问，数组中的第2个元素本人可以认为是长度，但是在一个数组中，拥有超过2个元素的话，就会有一些奇妙的效果，但是本人也尝试过这样设置，但是放出来就会非常怪。

所以本人想在此虚心求教一下，如果想设置所谓“重复使用旧音符”的效果，那么如何设置tune级音符的负数值。

**Comment by ayuusweetfish** [comment]
感谢关注~

第二个元素开始都是指长度，可以指示重复播放同一个音符，但添加段落反复的谜题时没有想好怎么修改格式，所以一直用着这个负数trick哈哈哈。实际上就是“每一次发出声音的时刻等于之前所有‘长度’之和”。

例如谜题内容是“567”但需要播放“567567”：
```plain
- [5, 3, -2] # 时刻     0 与 0+3=3
- [6, 3, -2] # 时刻 3-2=1 与 1+3=4
- [7, 3, 1]  # 时刻 4-2=2 与 2+3=5；下一个音符从 5+1=6 开始
```

确实比较不方便，谜题相关的说明也一直没有写，见谅啦🙊

**Comment by SleepyAsh0191** [comment]
非常感谢！
