### ISSUE TITLE
解题时使用实际乐曲 BPM？

### ISSUE THREAD

**Issue by HarukaMa** [kawa-yoiko/medle#3]
解题时似乎用了某个固定 BPM 播放答案，但这个数值和一些乐曲的实际 BPM 相差比较大，略微会影响一些判断。

希望可以加一个“使用实际 BPM”的选项。

虽然遇到认识的曲子可能就变得太简单了……

**Comment by ayuusweetfish** [comment]
感谢关注呀！

解题时的播放速度是根据每道题人为确定的，有时与原速不一致，主要是由于游戏本身以数字解谜为主，因此希望播放略快一些，避免拖慢游戏流程。通过音乐知识进行游戏属于进阶玩法，对玩家的音乐想象力有一定要求（当然也希望游戏可以帮助玩家提升哈哈哈哈~

虽然暂时没有作此调整的计划，但是后续改进过程中会考虑相关意见，感谢反馈！
