### ISSUE TITLE
[功能请求] 尝试次数随乐段长度动态调节

### ISSUE THREAD

**Issue by namasikanam** [kawa-yoiko/medle#6]
emm我也不太清楚怎么调节比较好呢？比如 $\lceil n / 2 \rceil$，还要根据大家的反馈调节一下qwq

（啊原来还是有开源仓库的……我……我一直以为没有来着……终于找到了……[捂脸]）

**Comment by ayuusweetfish** [comment]
暂定的做法是≥10个音符的题目有六次机会，其余仍然是五次，可能需要继续观察一下玩家反馈ww 谢谢呀
