### ISSUE TITLE
标注音名的表示方法

### ISSUE THREAD

**Issue by Pr0pHesyer** [kawa-yoiko/medle#8]
现有游戏在使用首调唱名法，或许也可以增加选项以使用固定唱名法
但是好像那个选项框只能容下两个全角字符的样子…五个就太突兀了

**Comment by ayuusweetfish** [comment]
现在“字母”选项对应固定音高，不过上下标的点暂时隐藏了，或许有空时会加一下吧\_(:з」∠)\_ 不知道会不会够用呀

**Comment by Pr0pHesyer** [comment]
> 现在“字母”选项对应固定音高，不过上下标的点暂时隐藏了，或许有空时会加一下吧_(:з」∠)_ 不知道会不会够用呀

现在已经够用了，毕竟还有唱名可用。
取决于想整活还是够用即可。比如数字和罗马完全是同一个东西，但还是都上了，照这么推理，两种标注方法都上比较好。

**Comment by ayuusweetfish** [comment]
明白了~

我觉得如果够用的话，这个的优先级就不太高，因为Medle的本意更倾向于普及音乐，而一般认为旋律方面的入门更适合使用首调，所以整个游戏基本都是围绕首调展开的，加入固定调的元素时最好克制一些。（反正习惯固定唱名的基本都是游戏中具有优势的内行了hhh）

不过确实在考虑未来重新设计这个方面，照顾所有玩家的习惯~谢谢建议呀！
